security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_memory: { memory: null }

    firewalls:
        register:
            pattern: ^/api/v1/users/register
            methods: [POST]
            security: false
        resend_activation_email:
            pattern: ^/api/v1/users/resend-activation-email
            methods: [POST]
            security: false
        docs:
            pattern: /api/v1/docs
            methods: [GET]
            security: false

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
