App\Entity\User:
    attributes:
        normalization_context:
            groups: [user_read]
    collectionOperations:
        register:
            method: POST
            path: /users/register
            controller: App\Api\Action\User\Register
            normalization_context:
                groups: [user_read]
            denormalization_context:
                groups: [user_write]
            openapi_context:
                summary: Register a new User
    itemOperations:
        get:
            method: GET
